version: "3"

services:
  myjenkins:
    image: tutorial/jenkins
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "8080"
      - "50000"
    ports:
      - "8080:8080"
      - "50000:50000"




